Fix (#998): Will not expire/delete cookie from session when Set-Cookie only sets Max-Age=0 without Expires
httpie/httpie pull request #1029
Opened 2021-02-05 12:14 UTC by LuckyDenis

Summary:
The reason why the `cookie` state information is lost is that when a response is received, the query library does not process `max-age=0`. It was decided to report the problem to the `requests` community and implement a temporary solution.

Done:
- [x] Fix issue #998
- [x] Add test for issue
- [x] Run `make test-all`
- [x] Make https://github.com/psf/requests/issues/5743

2021-02-05 12:51 UTC, LuckyDenis commented
I was unable to repeat this error on my macos. Can anyone try to reproduce it, and throw off the full error's log? 😓

2021-02-05 21:11 UTC, jakubroztocil requested changes

2021-02-05 21:11 UTC, jakubroztocil commented on httpie/utils.py
> +
This would be better as a new named function with a docstring for context & clarity.

2021-02-06 09:50 UTC, merged

2021-02-06 10:03 UTC, jakubroztocil commented
Thanks, @LuckyDenis 🥧

2021-02-08 15:40 UTC, LuckyDenis commented
@jakubroztocil, Thank you, I hope to participate in your wonderful project again ^_^

2021-03-25 13:29 UTC, george79d commented on AUTHORS.rst
> +* `Denis Belavin <https://github.com/LuckyDenis>`_
[]()

2021-03-25 13:29 UTC, george79d commented on AUTHORS.rst
> +* `Denis Belavin <https://github.com/LuckyDenis>`_
Thx

2021-03-25 13:29 UTC, george79d commented on httpie/utils.py
>      return [
```suggestion
     return [
```