Improve startup time with lazy loading some args
httpie/httpie pull request #1221
Opened 2021-11-30 13:00 UTC by isidentical

Fixes #1211

2021-11-30 15:43 UTC, jakubroztocil requested changes
Can we have a changelog entry with some numbers + tests for the lazy loading please?

2021-11-30 16:04 UTC, isidentical commented
> Can we have a changelog entry with some numbers + tests for the lazy loading please?

I am not really sure if this can be done through any unit tests, but I'll try add some unit tests to verify the behavior.

2021-12-01 18:15 UTC, jakubroztocil commented on CHANGELOG.md
> +
```suggestion
```

2021-12-01 18:16 UTC, merged

2021-12-01 18:16 UTC, jakubroztocil commented
🚤