Add workflow to test with pyOpenSSL active
httpie/httpie pull request #947
Opened 2020-07-01 13:45 UTC by gmelodie

Monkeypatches the `pyOpenSSL` module using [`urllib3.contrib.pyopenssl.inject_into_urllib3()`](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L20-L30).

Fixes #939.

2020-07-07 11:04 UTC, jakubroztocil commented on .github/workflows/build.yml
> +          HTTPIE_TEST_WITH_OPENSSL: ${{ matrix.pyopenssl }}
I’d rename the variable to `HTTPIE_TEST_WITH_PYOPENSSL`.

2020-07-07 11:05 UTC, jakubroztocil commented on tests/conftest.py
> +        try:
Here I’d rather try to explicitly import PyOpenSSL directly and show an error that it needs to be installed. The injecting part itself should not be inside a try…catch.

2020-07-07 11:06 UTC, jakubroztocil commented on tests/conftest.py
> +            raise ImportError("Unable to import pyOpenSSL")
`'`

2020-07-08 17:11 UTC, gmelodie commented
Wrote a test (`test_pyopenssl`) to check if `HTTPIE_TEST_WITH_PYOPENSSL` is set and `pyOpenSSL` is being used ([the same way that `urllib3` tests it](https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/pyopenssl.py#L124-L125))

2020-07-10 10:41 UTC, jakubroztocil commented
Hi @gmelodie, I see the tests are failing. Are you still working on this?

2020-07-10 12:07 UTC, gmelodie commented
@jakubroztocil Yes! I'll get down to that today. Last couple of days have been a bit messy.

2020-07-10 12:50 UTC, jakubroztocil commented
No worries, I was just curious.

2020-07-20 11:09 UTC, gmelodie commented
@jakubroztocil the tests seem to be working (they catch an error on windows). I'm not sure whether fixing this issue is in scope of this PR. If you think so, just give me a heads up and I'll try and work on that later today :)

2021-08-19 12:47 UTC, BoboTiG requested changes
@gmelodie could you rebase your PR on the master branch? I also left a review, that would be great if you could take it into account :)

2021-08-19 12:47 UTC, BoboTiG commented on tests/test_ssl.py
> +        assert urllib3.util.IS_PYOPENSSL is True
```suggestion
    using_pyopenssl = os.getenv('HTTPIE_TEST_WITH_PYOPENSSL', '0')
    if using_pyopenssl == '0':
        assert not urllib3.util.ssl_.IS_PYOPENSSL
        assert not urllib3.util.IS_PYOPENSSL
    else:
        assert urllib3.util.ssl_.IS_PYOPENSSL
        assert urllib3.util.IS_PYOPENSSL
```

2021-08-19 12:47 UTC, BoboTiG commented on tests/conftest.py
> +    urllib3.contrib.pyopenssl.extract_from_urllib3()
```suggestion
    if os.getenv('HTTPIE_TEST_WITH_PYOPENSSL', '0') == '1':
        try:
            import urllib3.contrib.pyopenssl
            urllib3.contrib.pyopenssl.inject_into_urllib3()
        except ImportError as exc:
            pytest.fail(f"Could not import PyOpenSSL: {exc!r}")

    yield
```

2021-09-23 08:37 UTC, closed without merging