provide password via environment variable `HTTPIE_PASSWORD`
httpie/httpie pull request #954
Opened 2020-07-08 13:46 UTC by OutOfBrain

This is a reviving #229 which enables passing of the auth password as environment variable.

The original pr had unfixed cr comments and was never addressed and was ultimately retracted it seems.
The initial comments are addressed in this pr.
If there are other comments related to this change I'm happy to fix them.

Solves my use case; in this pr:

- add support for auth password as env `HTTPIE_PASSWORD`
- add test (`make test-all` fine)
- update docs
- update changelog

2020-08-08 10:57 UTC, y352 commented on CHANGELOG.rst
> +* Provide password via environment variable ``HTTPIE_PASSWORD``
https://www.facebook.com/rafef.alyassry

2020-08-08 11:02 UTC, y352 commented on CHANGELOG.rst
> +* Provide password via environment variable ``HTTPIE_PASSWORD``
كيف احصل على حق الوصول

2020-08-08 11:30 UTC, y352 commented on tests/test_auth.py
>      assert r.json == {'authenticated': True, 'user': 'user'}
gkgk1979`

2020-08-08 11:31 UTC, y352 commented on tests/test_auth.py
> +def test_password_from_env(httpbin):
`gkgk1979`

2020-10-30 07:15 UTC, uncle9999 requested changes
[provide password via environment variable `HTTPIE_PASSWORD` (back_me)(SHA-26)

2020-11-02 02:55 UTC, uncle9999 commented
@uncle9999

2021-12-16 09:18 UTC, closed without merging